---
- name: Setup Kubernetes cluster
  hosts: all
  become: true
  roles:
    - role: common_install
    - role: kube_preinstall
    - role: master_install
      when: "'kube_masters' in group_names"
    - role: worker_install
      when: "'kube_workers' in group_names"
    - role: cilium_install
      when: "'kube_masters' in group_names"