---
- include_tasks: helm.yaml

- name: Add Cilium Helm repository
  shell: helm repo add cilium https://helm.cilium.io/

- name: Install Cilium
  shell: >
    KUBECONFIG=/etc/kubernetes/admin.conf
    helm install cilium cilium/cilium
    --version {{ cilium_version }}
    --namespace kube-system
    --set kubeProxyReplacement=true
    --set k8sServiceHost={{ hostvars['kube-master'].ansible_host }}
    --set k8sServicePort=6443
    --set ipam.mode="kubernetes"