---
- name: Add Kubernetes repository key
  apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
    state: present
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /"
    state: present
    filename: kubernetes.list

- name: Add CRI-O repository key
  apt_key:
    url: "https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key"
    state: present
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add CRI-O repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /"
    state: present
    filename: cri-o.list

- name: Install crun, CRI-O and kubeadm
  apt:
    name:
      - software-properties-common
      - crun
      - cri-o
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold kubeadm
  ansible.builtin.dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubelet
  ansible.builtin.dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubectl
  ansible.builtin.dpkg_selections:
    name: kubectl
    selection: hold

- name: Enable CRI-O
  systemd:
    name: crio.service
    state: started
    enabled: yes

- name: Load bridge kernel module
  modprobe:
    name: bridge
    state: present
    persistent: present

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: Set net.bridge.bridge-nf-call-iptables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf

- name: Set net.ipv4.ip_forward to 1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf